#!/bin/bash
createmenu ()
{
  #echo "Size of array: $#"
  #echo "$@"
  select option; do # in "$@" is the default
    if [ "$REPLY" -eq "$#" ];
    then
      echo "Exiting..."
      break;
    elif [ 1 -le "$REPLY" ] && [ "$REPLY" -le $(($#-1)) ];
    then
      #echo "You selected $option which is option $REPLY"
      break;
    else
      echo "Invalid input: Select a number 1-$#"
    fi
  done
}

rawOptions=$(find $HOME/.steam/steam/steamapps/common -name "Proton*" -printf $'%f\n')
readarray -t versions <<<"$rawOptions"
createmenu "${versions[@]}"
#PROTON_VERSION="3.7"
#PROTON_DIR=$HOME/.steam/steam/steamapps/common/Proton\ $PROTON_VERSION
PROTON_DIR="$HOME/.steam/steam/steamapps/common/$option"
PROTON_VERSION=${option:7:1000}

RUNNING="$1"
 
if [ ! -f "$PROTON_DIR/proton" ] ; then
    echo "Proton version $PROTON_VERSION not found!";
    exit
fi
 
if [ ! -f "$RUNNING" ] ; then
    echo "$RUNNING does not exist!";
    exit
fi
 
printf "Proton (\033[32m$PROTON_VERSION\033[0m) script found at\n  \033[32m$PROTON_DIR/proton\033[0m\n\n"
printf "Now running\n  \033[32m$PWD/$RUNNING\033[0m\n"
 
export STEAM_COMPAT_DATA_PATH="$HOME/.steam/steam/steamapps/compatdata"
export MOUNT_PATH="/media/d4/01D434E8CBD0E8F0"
 
PROTON_USE_WINED3D11=1 \
PROTON_USE_WINED3D=1 \
#PROTON_NO_D3D11=0 \
PROTON_NO_ESYNC=1 \
$HOME/.steam/steam/steamapps/common/Proton\ 3.7/proton \
run $RUNNING \

 
exit 0
