keys:
  # Users
  - &users:
    - &alan 111D6C0637278F94E3438D9B6B2B471B33BC4E0B
  # Hosts
  - &hosts:
    - &zwei-pc age1uyxxw4jhffq4py3uw09fxwjafk8n5smd5qs5av8w4yt9pjqz79psrlgues

creation_rules:
  - path_regex: hosts/zwei-pc/secrets.ya?ml$
    key_groups:
      - age:
          - *zwei-pc
        pgp:
          - *alan

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *zwei-pc
        pgp:
          - *alan
