keys:
  # Users
  - &users:
    - &alan 111D6C0637278F94E3438D9B6B2B471B33BC4E0B
  # Hosts
  - &hosts:
    - &gamer-think age1wxml3qqg7r23u6w3ppj59lrljrqveah70l2dyg35trwz9gzwcakse7m496
    - &zwei-pc age1n54qel5raqedqst3n6mtmzu5ptyrrddfznzpxrpjev3vaapd3fvsxj6vyr

creation_rules:
  - path_regex: hosts/gamer-think/secrets.ya?ml$
    key_groups:
      - age:
          - *gamer-think
        pgp:
          - *alan
  - path_regex: hosts/zwei-pc/secrets.ya?ml$
    key_groups:
      - age:
          - *zwei-pc
        pgp:
          - *alan

  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
      - age:
          - *gamer-think
          - *zwei-pc
        pgp:
          - *alan
