#!/bin/bash
HOSTNAME=$(hostname)

gap=10

bspc config top_padding     $((25-$gap))
bspc config bottom_padding    $((25-$gap))
bspc config left_padding    -$gap
bspc config right_padding   -$gap
bspc config window_gap      $gap

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width          1

bspc config focused_border_color  \#395084
bspc config normal_border_color   $(xgetres background)
#bspc config normal_border_color  \#111824

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       false # leave off for negative padding
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config single_monocle        true
bspc config initial_polarity      first_child

bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_side

bspc config external_rules_command $HOME/.config/bspwm/external_rules

bash "$HOME/.config/bspwm/host-configs/$(hostname)"

bspc rule -a Gimp desktop='^7' state='floating'
bspc rule -a minecraft-launcher state='floating'
bspc rule -a discord desktop='^9' follow=off
bspc rule -a Spotify desktop='^10' follow=off state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a mpv focus=off state=floating
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on

bspc rule -a albert state=floating follow=on sticky=on border=off focus=on
bspc rule -a Pavucontrol state=floating sticky=on

