#! /bin/sh

#transmission-daemon &
xsetroot -cursor_name left_ptr &
exec sxhkd &
picom --experimental-backends --backend glx -b &
killall dunst; dunst &
#killall polybar; ~/.script/dock.sh &>/tmp/dock.log
#auto-connect-bt.sh &
remaps &

pidof albert || albert &

rm /tmp/POLYBAR_*
killall polybar; ~/.script/launch_polybar.sh &>/tmp/polybar.log
#timer-checkupdates.sh &
~/.script/SPTN.sh &
~/.script/MO.sh &

feh --no-fehbg --bg-fill "$HOME/.config/bspwm/wallpaper"
source $HOME/.config/env

bspc monitor DVI-D-0 -d 1 2 3 4 5
bspc monitor DP-2    -d 6 7 8 9 10
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        	1
bspc config window_gap          	5

bspc config top_padding			30
bspc config bottom_padding		30

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config single_monocle	 	true
bspc config focused_border_color 	\#FEFEFE
bspc config normal_border_color 	\#111824
bspc config initial_polarity 		first_child

bspc config pointer_modifier 		mod4
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_sidie

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a Alacritty desktop='^1' follow=on state=pseudo_tiled
bspc rule -a qutebrowser desktop='^2' 
bspc rule -a newsboat desktop='^4' follow=on state=pseudo_tiled
bspc rule -a Vim desktop='^5' follow=on state=pseudo_tiled
bspc rule -a Zathura desktop='^6' follow=on state=pseudo_tiled
bspc rule -a Sxiv desktop='^6' follow=off 
bspc rule -a Gimp desktop='^7' state=floating 
bspc rule -a minecraft-launcher desktop='^8'
bspc rule -a discord desktop='^9' follow=off  
bspc rule -a Spotify desktop='^10' follow=off state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a mpv focus=off state=floating
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on
bspc rule -a lf locked=on sticky=on state=floating hidden=on
bspc rule -a cool-retro-term state=pseudo_tiled
bspc rule -a Surf state=tiled

bspc rule -a albert state=floating follow=on sticky=on border=off focus=on
bspc rule -a Pavucontrol state=floating sticky=on

bspc desktop '^3' -l monocle
bspc desktop '^5' -l monocle

# SCRATCHPADS

sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $sid)" ] \
	&& alacritty -t scratchpad --class scratch,scratchpad -d 35 10\
	& sleep 1 \
	&& sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$sid" > /tmp/scratchID ;

cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $cid)" ] \
	&& alacritty -t calculator --class calc,scratchpad -d 35 10 -e bash -c "echo "" && calc -d" \
	& sleep 1 \
	&& cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$cid" > /tmp/calcID ;

# LF
lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $lid)" ] \
	&& alacritty --config-file .config/alacritty/lf.yml -t lf --class lf,lf -d 75 16 -e startlf \
	& sleep 1 \
	&& lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
	&& echo "$lid" > /tmp/lfID;

# Because spotify won't listen
setsid -f start-spotify > /dev/null 2>&1 &
