#!/bin/bash
HOSTNAME=$(hostname)

$HOME/.xinitrc

bash $HOME/.config/bspwm/bspc

#source $HOME/.config/env

# Because spotify won't listen
setsid -f start-spotify > /dev/null 2>&1 &

# OTHER APPLICATIONS

kill $(pgrep eww_fullscreen_workaround -f)
~/.config/bspwm/scripts/eww_fullscreen_workaround.sh &

pidof sxhkd || exec sxhkd &

pidof picom || picom -b &

pidof dunst || dunst &
pidof albert || albert &
#pidof polybar || ~/.script/launch_polybar.sh &>/tmp/polybar.log

./scripts/open_eww.sh &

#timer-checkupdates.sh &
~/.script/SPTN.sh &
~/.script/MO.sh &


feh --no-fehbg --bg-scale "$HOME/Pictures/wallpapers" -z &
#hsetroot -solid $(xgetres background)
xsetroot -cursor_name left_ptr &
