#!/bin/sh
xinput set-prop 12 404 0.7  # accel speed
xinput set-prop 12 407 0, 1 # 2nd accel profile
xinput set-prop 12 394 0    # disable while typing

gap=2

bspc config top_padding     $((25-$gap))
bspc config bottom_padding    $((25-$gap))
bspc config left_padding    -$gap
bspc config right_padding   -$gap
bspc config window_gap      $gap
